version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running pre-build tasks...
      - npm run lint

  build:
    commands:
      - echo Building the project...
      - npm run build

artifacts:
  files:
    - 'dist/**/*'
